version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  pgvector:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5433:5433"
    depends_on:
      - db
    volumes:
      - pgvector-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./cmd
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/yourdb?sslmode=disable
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - pgvector
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/yourdb -user=youruser -password=yourpassword migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

volumes:
  db-data:
  redis-data:
  pgvector-data:
